
obj-y += adsp_6210.o
obj-y += adsp_6220.o
obj-y += adsp_6225.o
obj-y += adsp_5200.o
obj-y += adsp_6120.o
obj-y += adsp_6150.o



obj-y += adsp.o adsp_driver.o
obj-y += adsp_video_verify_cmd.o
obj-y += adsp_videoenc_verify_cmd.o
obj-y += adsp_jpeg_verify_cmd.o adsp_jpeg_patch_event.o 
obj-y += adsp_vfe_verify_cmd.o adsp_vfe_patch_event.o 
obj-y += adsp_lpm_verify_cmd.o 
obj-y += audio_out.o audio_in.o audio_mp3.o audmgr.o audpp.o
obj-y += snd.o
obj-y += amss_para.o
obj-y += external.o

